---
# Source: opencart/charts/mariadb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-mariadb
  labels:
    app: "mariadb"
    chart: "mariadb-7.4.0"
    release: "release-name"
    heritage: "Tiller"
type: Opaque
data:
  mariadb-root-password: "U2gzSm10OGRDVA=="
  
  mariadb-password: "a1YwZlVsRUdPbQ=="
